local settings = {
  -- every line should be same width without escaped \
  header = {
    type = "text",
    oldfiles_directory = false,
    align = "center",
    fold_section = false,
    title = "Header",
    margin = 5,
    content = {
      "                                                                             ",
      "                                    …¡=!¸                                    ",
      "                              ÕðøG¶¶¶¶¶¶¶¶¶GGðÔ                              ",
      "                           âø¶¶¶¶¶j       v¶¶¶¶¶ð¶                           ",
      "                        ¿ß¶¶¶Ð’                X¶¶¶8)                        ",
      "                       ¶¶¶¶                       ¶¶¶¶                       ",
      "                     h¶¶¶^          !âG¶¶¶p¶¶¶â    “¶¶¶à                     ",
      "                    ß¶¶ã          ð¶¶¶ã˜     é       ¶¶¶m                    ",
      "                   s¶¶Ú         ð¶*   ðmAs            ø¶¶Í                   ",
      "                   ¶¶ð         ø˜ÔGV      8            ð¶¶                   ",
      "                  Ü¶¶ã        8¶ ¶m8@                  ¶¶¶Ü                  ",
      "                  ¶¶¶         Ó¶G péÇ                   ø¶¶                  ",
      "                  ¶¶¶          â¶Gz Gt  …ø‹             ¶¶¶                  ",
      "                  ¶¶¶           GG¶¶ðœ   ãâë            ¶¶¶                  ",
      "                  G¶¶£             G¶¶¶ø8A øU          V¶¶m                  ",
      "                   ¶¶G                 ¶¶¶GžD          G¶¶                   ",
      "                   é¶¶m                  ¶¶8|         p¶¶G                   ",
      "                    ¶¶¶ø                  ¶¶8        ø¶¶¶                    ",
      "                     ¶¶¶8                 ¶¶â       é¶¶p                     ",
      "                      ã¶¶¶ù              ¶¶¶ë     ù¶¶¶¶                      ",
      "                        ã¶¶¶8          G¶¶GÛ    ã¶¶¶G                        ",
      "                          âm¶¶¶¶¶¶¶¶¶¶¶¶$ð   ¶¶¶¶¶ë                          ",
      "                             ¶â¶G¶GGâGp    ¶¶¶¶m                             ",
      "                                        Gâ¶õ                                 ",
      "                                                                             ",
    },
    highlight = "Statement",
    default_color = "",
    oldfiles_amount = 0,
  },
  body = {
    type = "mapping",
    oldfiles_directory = false,
    align = "center",
    fold_section = false,
    title = "Basic Commands",
    margin = 5,
    content = {
      { "  Find File", "Telescope find_files", "<leader>ff" },
      { "󰍉  Find Word", "Telescope live_grep", "<leader>fg" },
      { "  Recent Files", "Telescope oldfiles", "<leader>fr" },
      { "  File Explorer", "Telescope file_browser", "<leader>fe" },
      { "  Colorschemes", "Telescope colorscheme", "<leader>fC" },
      { "  New File", "lua require'startup'.new_file()", "<leader>nf" },
    },
    highlight = "String",
    default_color = "",
    oldfiles_amount = 0,
  },
  footer = {
    type = "text",
    oldfiles_directory = false,
    align = "center",
    fold_section = false,
    title = "Footer",
    margin = 2,
    content = { "nil70n" },
    highlight = "Number",
    default_color = "",
    oldfiles_amount = 0,
  },
  options = {
    mapping_keys = true,
    cursor_column = 0.5,
    empty_lines_between_mappings = true,
    disable_statuslines = true,
    paddings = { 1, 3, 1, 0 },
  },
  mappings = {
    execute_command = "<CR>",
    open_file = "o",
    open_file_split = "<c-o>",
    open_section = "<TAB>",
    open_help = "?",
  },
  colors = {
    background = "#1f2227",
    folded_section = "#56b6c2",
  },
  parts = { "header", "body", "footer" },
}

return {
  "startup-nvim/startup.nvim",
  dependencies = { "nvim-telescope/telescope.nvim", "nvim-lua/plenary.nvim" },
  opts = settings
}
